import {
  defaultSettingsAbcdef,
  defaultSettingsAbyss,
  defaultSettingsAndroidstudio,
  defaultSettingsAndromeda,
  defaultSettingsAtomone,
  defaultSettingsAura,
  defaultSettingsBasicDark,
  defaultSettingsBasicLight,
  defaultSettingsBbedit,
  defaultSettingsBespin,
  defaultSettingsConsoleDark,
  defaultSettingsConsoleLight,
  defaultSettingsCopilot,
  defaultSettingsDracula,
  defaultSettingsDuotoneDark,
  defaultSettingsDuotoneLight,
  defaultSettingsEclipse,
  defaultSettingsGithubDark,
  defaultSettingsGithubLight,
  defaultSettingsGruvboxDark,
  defaultSettingsGruvboxLight,
  defaultSettingsKimbie,
  defaultSettingsMaterial,
  defaultSettingsMaterialDark,
  defaultSettingsMaterialLight,
  defaultSettingsMonokai,
  defaultSettingsMonokaiDimmed,
  defaultSettingsNoctisLilac,
  defaultSettingsNord,
  defaultSettingsOkaidia,
  defaultSettingsQuietlight,
  defaultSettingsRed,
  defaultSettingsSolarizedDark,
  defaultSettingsSolarizedLight,
  defaultSettingsSublime,
  defaultSettingsTokyoNight,
  defaultSettingsTokyoNightDay,
  defaultSettingsTokyoNightStorm,
  defaultSettingsTomorrowNightBlue,
  defaultSettingsVscodeDark,
  defaultSettingsWhiteDark,
  defaultSettingsWhiteLight,
  defaultSettingsXcodeDark,
  defaultSettingsXcodeLight,
} from "@uiw/codemirror-themes-all";

const themes = {
  abyss: defaultSettingsAbyss,
  abcdef: defaultSettingsAbcdef,
  androidstudio: defaultSettingsAndroidstudio,
  andromeda: defaultSettingsAndromeda,
  atomone: defaultSettingsAtomone,
  aura: defaultSettingsAura,
  basicDark: defaultSettingsBasicDark,
  basicLight: defaultSettingsBasicLight,
  bbedit: defaultSettingsBbedit,
  bespin: defaultSettingsBespin,
  consoleDark: defaultSettingsConsoleDark,
  consoleLight: defaultSettingsConsoleLight,
  copilot: defaultSettingsCopilot,
  dracula: defaultSettingsDracula,
  duotoneDark: defaultSettingsDuotoneDark,
  duotoneLight: defaultSettingsDuotoneLight,
  eclipse: defaultSettingsEclipse,
  githubDark: defaultSettingsGithubDark,
  githubLight: defaultSettingsGithubLight,
  gruvboxDark: defaultSettingsGruvboxDark,
  gruvboxLight: defaultSettingsGruvboxLight,
  kimbie: defaultSettingsKimbie,
  material: defaultSettingsMaterial,
  materialDark: defaultSettingsMaterialDark,
  materialLight: defaultSettingsMaterialLight,
  monokaiDimmed: defaultSettingsMonokaiDimmed,
  monokai: defaultSettingsMonokai,
  noctisLilac: defaultSettingsNoctisLilac,
  nord: defaultSettingsNord,
  okaida: defaultSettingsOkaidia,
  quietlight: defaultSettingsQuietlight,
  red: defaultSettingsRed,
  solarizedDark: defaultSettingsSolarizedDark,
  solarizedLight: defaultSettingsSolarizedLight,
  sublime: defaultSettingsSublime,
  tokyoNightDay: defaultSettingsTokyoNightDay,
  tokyoNightStorm: defaultSettingsTokyoNightStorm,
  tokyoNight: defaultSettingsTokyoNight,
  tomorrowNightBlue: defaultSettingsTomorrowNightBlue,
  vscodeDark: defaultSettingsVscodeDark,
  whiteDark: defaultSettingsWhiteDark,
  whiteLight: defaultSettingsWhiteLight,
  xcodeDark: defaultSettingsXcodeDark,
  xcodeLight: defaultSettingsXcodeLight,
};

export default themes;
